worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: true

server-port: 8080

# messenger-user-management_db-1 is the service name + _ + filename of the messenger.sql
dbconnection: 'postgresql://testsuite@localhost:15433/messenger-user-management'
